### ISSUE TITLE
Susahnya melakukan pull request

### ISSUE THREAD

**Issue by Arsfiqball** [BesutKode/BesutKode.github.io#241]
Sepertinya terlalu banyak yang mengedit file yang sama bersamaan, sehingga sering terjadi merge conflict. Bagaimana ini?

**Comment by jayvdb** [comment]
It is intentional.

It is only trouble for people who try to do their pull request on the last day, or do not know git already.

Russian roulette for people to learn git properly.

**Comment by jayvdb** [comment]
It is your lucky day.  I added you manually.

https://github.com/BesutKode/BesutKode.github.io/commit/af521670eeb6a07079b49ffbdd4680d506dec5d2

**Comment by Arsfiqball** [comment]
Yah thank you 😂
I'll do my best sir!

**Comment by Arsfiqball** [comment]
a star for this repo.
