### ISSUE TITLE
Some finished task 2 become not found

### ISSUE THREAD

**Issue by berviantoleo** [BesutKode/BesutKode.github.io#310]
Some finished task 2 become not found. Here the link.
https://besutkode.github.io/uni-task-2-arrizalamin/
https://besutkode.github.io/uni-task-2-prasastoadi/
https://besutkode.github.io/uni-task-2-edawine/

Maybe it failed to deploy in github page?

**Comment by laymonage** [comment]
IIRC, it's because they haven't successfully configured it to work with gh-pages.

>Maybe it failed to deploy in github page?  

In other words, yes, it did (or at least I think so).
