### ISSUE TITLE
Typo on Mentor Description

### ISSUE THREAD

**Issue by wisn** [BesutKode/BesutKode.github.io#318]
I think it's a typo on mentor description. To be precise, it's on `John Vandenberg` section and `Yana Agun Siswanto` section.

On `John Vandenberg`:  "...dari Queensland University of Technology, Australia **and** telah menjadi mentor untuk...". It's should be "dan" in Bahasa Indonesia.

On `Yana Agun Siswanto`: "Yana Agun Siswanto **ada** pemenang Grand Prize Besut Kode Universitas 2016." It's should be "adalah".

**Comment by laymonage** [comment]
Closed per https://github.com/BesutKode/BesutKode.github.io/pull/319.
