### ISSUE TITLE
Bad Register Modal on Firefox

### ISSUE THREAD

**Issue by wisn** [BesutKode/BesutKode.github.io#324]
In my browser, Firefox, the register modal looked bad. Moreover, I can't scroll the modal so I can't fill up the form.

![screenshot from 2017-08-21 12-04-53](https://user-images.githubusercontent.com/8147926/29504371-717d2c02-8669-11e7-9516-2f5e13114def.png)

**Comment by pamungkaski** [comment]
okey

**Comment by jayvdb** [comment]
Closed with #325
